/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package magnumopusms;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.security.*; 
import java.math.*;
import javax.swing.JOptionPane;
import static magnumopusms.login.fieldUsername;


/**
 *
 * @author a100519
 */
public class mainform extends javax.swing.JFrame {
Connection con = null;
    public mainform() {
        initComponents();
        con=dbConnection.getConnection();
    }
    
    public void executeSQLQuery(String query){
        Statement st;
        try{
            st = con.createStatement();
            if(st.executeUpdate(query) == 1){
                System.out.println ("Sucesso");
            }else{
                JOptionPane.showMessageDialog(null, "Erro");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    static int idUser;
    static String userAtual;
    public void setUserAtual() {
        PreparedStatement ps;
        ResultSet rs;
        String query = "SELECT * FROM login WHERE id = ?";
        
        try{
            ps= dbConnection.getConnection().prepareStatement(query);
            
            ps.setInt(1, idUser);
            
            rs = ps.executeQuery();
            if(rs.next()){
                userAtual = (rs.getString("nome_func"));
            }
        }catch(Exception e){}
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        backgroundPanel = new javax.swing.JPanel();
        labelMOpus = new javax.swing.JLabel();
        buttonExit = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        buttonClients = new javax.swing.JButton();
        buttonWorkers = new javax.swing.JButton();
        buttonCategorys = new javax.swing.JButton();
        buttonOrders = new javax.swing.JButton();
        buttonUser = new javax.swing.JButton();
        buttonInventory = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        buttonLogout = new javax.swing.JButton();

        jButton5.setBackground(new java.awt.Color(255, 204, 102));
        jButton5.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/magnumopusms/images/icons8-inventory-64.png"))); // NOI18N
        jButton5.setText("Inventário");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        backgroundPanel.setBackground(new java.awt.Color(106, 49, 127));

        labelMOpus.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        labelMOpus.setForeground(new java.awt.Color(255, 255, 255));
        labelMOpus.setText("Magnum Opus");

        buttonExit.setBackground(new java.awt.Color(255, 204, 102));
        buttonExit.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        buttonExit.setText("X");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        buttonClients.setBackground(new java.awt.Color(255, 204, 102));
        buttonClients.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        buttonClients.setIcon(new javax.swing.ImageIcon(getClass().getResource("/magnumopusms/images/icons8-consumer-64.png"))); // NOI18N
        buttonClients.setText("Clientes");
        buttonClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClientsActionPerformed(evt);
            }
        });

        buttonWorkers.setBackground(new java.awt.Color(255, 204, 102));
        buttonWorkers.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        buttonWorkers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/magnumopusms/images/icons8-cashier-60.png"))); // NOI18N
        buttonWorkers.setText("Funcionários");
        buttonWorkers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWorkersActionPerformed(evt);
            }
        });

        buttonCategorys.setBackground(new java.awt.Color(255, 204, 102));
        buttonCategorys.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        buttonCategorys.setIcon(new javax.swing.ImageIcon(getClass().getResource("/magnumopusms/images/icons8-elective-50.png"))); // NOI18N
        buttonCategorys.setText("Categorias");
        buttonCategorys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCategorysActionPerformed(evt);
            }
        });

        buttonOrders.setBackground(new java.awt.Color(255, 204, 102));
        buttonOrders.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        buttonOrders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/magnumopusms/images/icons8-delivery-box-64.png"))); // NOI18N
        buttonOrders.setText("Encomendas");
        buttonOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOrdersActionPerformed(evt);
            }
        });

        buttonUser.setBackground(new java.awt.Color(255, 204, 102));
        buttonUser.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        buttonUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/magnumopusms/images/icons8-user-64.png"))); // NOI18N
        buttonUser.setText("Utlizador");
        buttonUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUserActionPerformed(evt);
            }
        });

        buttonInventory.setBackground(new java.awt.Color(255, 204, 102));
        buttonInventory.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        buttonInventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/magnumopusms/images/icons8-inventory-64.png"))); // NOI18N
        buttonInventory.setText("Inventário");
        buttonInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInventoryActionPerformed(evt);
            }
        });

        welcomeLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        welcomeLabel.setText("welcomeLabel");

        buttonLogout.setBackground(new java.awt.Color(255, 204, 102));
        buttonLogout.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        buttonLogout.setText("LOGOUT");
        buttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCategorys, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonClients, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonUser, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonWorkers, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(welcomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonLogout)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonClients, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCategorys, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonUser, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonWorkers, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(welcomeLabel)
                    .addComponent(buttonLogout))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(labelMOpus)
                .addGap(225, 225, 225)
                .addComponent(buttonExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonExit)
                    .addComponent(labelMOpus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonExitActionPerformed

    private void buttonClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClientsActionPerformed
        clients clients = new clients();
        clients.setVisible(true);
        clients.pack();
        clients.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_buttonClientsActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void buttonWorkersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWorkersActionPerformed
        PreparedStatement ps;
        ResultSet rs;
        String tipo = ("admin");
        
        String query = "SELECT * FROM login  WHERE id = ? AND tipo_user = ?";
        try{
            ps = dbConnection.getConnection().prepareStatement(query);
            
            ps.setInt(1, idUser);
            ps.setString(2, tipo);
            
            rs = ps.executeQuery();
        if (rs.next()){
            funcionarios funcionarios = new funcionarios();
            funcionarios.setVisible(true);
            funcionarios.pack();
            funcionarios.setLocationRelativeTo(null);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Apenas administradores podem aceder a esta área!", "Falta de permissões", 2);
        }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_buttonWorkersActionPerformed

    private void buttonOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOrdersActionPerformed
        orders orders = new orders();
        orders.setVisible(true);
        orders.pack();
        orders.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_buttonOrdersActionPerformed

    private void buttonUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUserActionPerformed
        PreparedStatement ps;
        ResultSet rs;
        String query= "SELECT * FROM login WHERE id = '"+idUser+"'";
        try{
            ps = dbConnection.getConnection().prepareStatement(query);
            rs = ps.executeQuery();
            while (rs.next()){
                //MessageDigest m=MessageDigest.getInstance("MD5");
                //m.update(s.getBytes(),0,s.length());
                utilizador utilizador = new utilizador();
                utilizador.setVisible(true);
                utilizador.pack();
                utilizador.setLocationRelativeTo(null);
                utilizador.fieldNomeFunc.setText(rs.getString("nome_func"));
                utilizador.fieldUsername.setText(rs.getString("username"));
                utilizador.fieldPassword.setText(rs.getString("password"));
                this.dispose();
            }
        }catch(Exception ex){}
    }//GEN-LAST:event_buttonUserActionPerformed

    private void buttonInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInventoryActionPerformed
        products products = new products();
        products.setVisible(true);
        products.pack();
        products.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_buttonInventoryActionPerformed

    private void buttonCategorysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCategorysActionPerformed
        categorias categorias = new categorias();
        categorias.setVisible(true);
        categorias.pack();
        categorias.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_buttonCategorysActionPerformed

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        login login = new login();
        login.setVisible(true);
        login.pack();
        login.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_buttonLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton buttonCategorys;
    private javax.swing.JButton buttonClients;
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonInventory;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton buttonOrders;
    private javax.swing.JButton buttonUser;
    private javax.swing.JButton buttonWorkers;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel labelMOpus;
    private javax.swing.JPanel mainPanel;
    public javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
